- name: Set Default
  ansible.builtin.set_fact:
    directory_match_status: "check failed"
    


- name: Verify the presence of DirectoryMatch directive for .svn
  ansible.builtin.shell: |
    if grep -q '<DirectoryMatch "/\.svn">' {{ apache_conf_dir }}/conf/httpd.conf && \
       grep -q 'Require all denied' {{ apache_conf_dir }}/conf/httpd.conf; then
      echo "DirectoryMatch directive for .svn is set correctly"
    else
      echo "DirectoryMatch directive for .svn is NOT set correctly" && exit 1
    fi
  register: directory_match_check
  ignore_errors: yes


  - name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ directory_match_check.stderr }}"
  when: directory_match_check.rc != 0
  ignore_errors: yes


- name: Set the directory match status
  ansible.builtin.set_fact:
    directory_match_status: "{{ 'not compliant' if directory_match_check.rc != 0 else 'compliant' }}"
  ignore_errors: yes
  

- name: Log the compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},5.12,DirectoryMatch .svn Checks,{{ directory_match_status }},{{ error_desc | trim }}"
    create: yes
  delegate_to: localhost
