- name: Set Default status
  ansible.builtin.set_fact:
    non_root_files_status: "not compliant"

- name: Identify files in the Apache directory not owned by root
  ansible.builtin.shell: "find {{ apache_bin_dir }} ! -user root"
  register: non_root_files_check
  changed_when: false
  failed_when: non_root_files_check.rc != 0
  ignore_errors: true


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ non_root_files_check.stderr }}"
  when: non_root_files_check.rc != 0
  ignore_errors: yes


- name: Determine if non-root files exist
  ansible.builtin.set_fact:
    non_root_files_status: "{{ 'not compliant' if non_root_files_check.stdout != '' else 'compliant' }}"
  ignore_errors: true

- name: Append non-root files status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},3.4,Apache Directories and Files Are Owned By Root,{{ non_root_files_status }},{{ error_desc | trim }}"
    insertafter: EOF
  delegate_to: localhost
