- name: Set default apache_shell_status
  ansible.builtin.set_fact:
    apache_shell: ""
    apache_shell_status: "not compliant"

- name: Check Apache login shell
  ansible.builtin.getent:
    database: passwd
    key: apache
  register: apache_shell_check
  changed_when: false
  ignore_errors: true


- name: Determine Apache login shell
  ansible.builtin.set_fact:
    apache_shell: "{{ apache_shell_check.passwd.shell if apache_shell_check is defined and apache_shell_check.passwd is defined and apache_shell_check.passwd.shell is defined else '' }}"
  ignore_errors: true


- name: Determine Apache login shell status
  ansible.builtin.set_fact:
    apache_shell_status: "{{ 'compliant' if apache_shell in ['/sbin/nologin', '/dev/null'] else 'not compliant' }}"
  ignore_errors: true


- name: Append Apache login shell status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},3.2,apache_login_shell,{{ apache_shell_status }}"
    insertafter: EOF
  delegate_to: localhost
