- name: Set Default
  ansible.builtin.set_fact:
    apache_user: "not compliant"
    apache_user_status: "not compliant"


- name: Check Apache User Configuration
  ansible.builtin.shell: "grep '^User ' {{ apache_conf_dir }}/conf/httpd.conf"
  register: apache_user_check
  changed_when: false
  failed_when: false 
  ignore_errors: true 

  
- name: Set Apache user variable
  ansible.builtin.set_fact:
    apache_user: "{{ apache_user_check.stdout.split()[1] if apache_user_check.stdout | length > 0 else 'not found' }}"
  ignore_errors: true 


- name: Check if Apache user is non-root
  ansible.builtin.shell: "id -u {{ apache_user }}"
  register: apache_user_id
  changed_when: false
  failed_when: false  
  ignore_errors: true 
  when: apache_user != 'not found'


- name: Determine if Apache user UID is less than 1000
  ansible.builtin.set_fact:
    apache_user_status: >-
      {% if apache_user == 'not found' %}
        not compliant
      {% elif apache_user_id.stdout | length > 0 and apache_user_id.stdout | int < 1000 %}
        compliant
      {% else %}
        not compliant
      {% endif %}
  ignore_errors: true 
  

- name: Append Apache user status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},3.1,apache_user,{{ apache_user_status | trim }}"
  delegate_to: localhost
