- name: Set Default
  ansible.builtin.set_fact:
    autoindex_status: "check failed"


- name: Check if autoindex module is enabled
  ansible.builtin.shell: "{{ apache_bin_dir }}/httpd -M | grep autoindex"
  register: autoindex_check
  failed_when: autoindex_check.rc != 0
  changed_when: false
  ignore_errors: true

- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ autoindex_check.stderr }}"
  when: autoindex_check.rc != 0
  ignore_errors: yes


- name: Determine autoindex status
  ansible.builtin.set_fact:
    autoindex_status: "{{ 'compliant' if autoindex_check.rc == 0 else 'not compliant' }}"
  ignore_errors: true


- name: Append autoindex status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},2.5,autoindex,{{ autoindex_status }} {{ error_desc | trim }}"
  delegate_to: localhost
