- name: Set Default status 
  ansible.builtin.set_fact:
    test_cgi_status: "check failed"


- name: Check if test-cgi script exists in cgi-bin directory
  ansible.builtin.shell: |
    if [ -d "/var/www/cgi-bin/" ]; then
      find "/var/www/cgi-bin/" -name "test-cgi" -type f && exit 0
    fi
    exit 1
  register: test_cgi_check
  changed_when: false
  failed_when: false
  ignore_errors: yes


- name: Set test_cgi_status compliance
  ansible.builtin.set_fact:
    test_cgi_status: "{{ 'compliant' if test_cgi_check.rc != 0 else 'not compliant' }}"
  ignore_errors: yes


- name: Append test_cgi_status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.6,test_cgi_check_id,{{ test_cgi_status }}"
    insertafter: EOF
  delegate_to: localhost
