- name: Set Default status 
  ansible.builtin.set_fact:
    error_desc: ""
    test_cgi_status: "check failed"


- name: Check if test-cgi script exists in cgi-bin directory
  ansible.builtin.command:
    cmd: find /var/www/cgi-bin/ -name "test-cgi" -type f
  register: test_cgi_check
  changed_when: false
  ignore_errors: yes  


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ test_cgi_check.stderr }}"
  when: test_cgi_check.rc != 0
  ignore_errors: yes


- name: Set test_cgi_status compliance
  ansible.builtin.set_fact:
    test_cgi_status: "{{ 'compliant' if test_cgi_check.rc != 0 or test_cgi_check.stdout == '' else 'not compliant' }}"
  ignore_errors: yes


- name: Append test_cgi_status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.6,test_cgi_check_id,{{ test_cgi_status }},{{ error_desc | trim }}"
    insertafter: EOF
  delegate_to: localhost
