- name: Set Default status
  ansible.builtin.set_fact:
    cgi_status: "check failed"


- name: Check if printenv CGI is installed in cgi-bin directory
  ansible.builtin.command:
    cmd: find /var/www/cgi-bin/ -name "printenv" -type f
  register: printenv_check
  changed_when: false
  ignore_errors: yes


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ printenv_check.stderr }}"
  when: printenv_check.rc != 0
  ignore_errors: yes


- name: Set cgi-bin compliance status
  ansible.builtin.set_fact:
    cgi_status: "{{ 'compliant' if printenv_check.rc != 0 or printenv_check.stdout == '' else 'not compliant' }}"
  ignore_errors: yes


- name: Append cgi-bin compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.5,cgi_bin_compliance,{{ cgi_status }}, {{ error_desc | trim }}"
    insertafter: EOF
  delegate_to: localhost
  
