- name: Set Default status
  ansible.builtin.set_fact:
    cgi_status: "check failed"


- name: Check if printenv CGI is installed in cgi-bin directory
  ansible.builtin.shell: |
    if [ -d "/var/www/cgi-bin/" ]; then
      find "/var/www/cgi-bin/" -name "printenv" -type f && exit 0
    fi
    exit 1
  register: printenv_check
  changed_when: false
  ignore_errors: yes


- name: Set cgi-bin compliance status
  ansible.builtin.set_fact:
    cgi_status: >-
      {%- if printenv_check.rc == 0 -%}
        not compliant
      {%- else -%}
        compliant
      {%- endif -%}
  ignore_errors: yes


- name: Append cgi-bin compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.5,cgi_bin_compliance,{{ cgi_status }}"
    insertafter: EOF
  delegate_to: localhost
  