- name: Check for TraceEnable directive
  ansible.builtin.command: >-
    grep -i '^TraceEnable\s\+off$' {{ apache_conf_dir }}/conf/httpd.conf
  register: trace_enable_check
  changed_when: false
  failed_when: false

- name: Set compliance status for TraceEnable
  ansible.builtin.set_fact:
    trace_enable_status: "{{ 'compliant' if trace_enable_check.rc == 0 else 'not_compliant' }}"

- name: Write compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},5.8,Apache TraceEnable Configuration,{{ trace_enable_status }}"
    create: yes
  delegate_to: localhost
  