- name: Set Default
  set_fact:
    ssl_nss_status: "check failed"


- name: Verify that mod_ssl or mod_nss is loaded in the Apache configuration
  shell: |
    {{ apache_bin_dir }}/httpd -M | grep -E 'ssl_module|nss_module'
  register: ssl_nss_check
  ignore_errors: yes


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ ssl_nss_check.stderr }}"
  when: ssl_nss_check.rc != 0
  ignore_errors: yes

- name: Set compliance status for SSL/NSS modules
  set_fact:
    ssl_nss_status: "{{ 'compliant' if ssl_nss_check.stdout else 'not compliant' }}"
  ignore_errors: yes


- name: Record compliance status for SSL/NSS modules
  lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},7.1,ssl_nss_module_status,{{ ssl_nss_status }}, {{ error_desc | trim }}"
    create: yes
  delegate_to: localhost
