- name: Verify that mod_ssl or mod_nss is loaded in the Apache configuration
  shell: |
    # Check if either mod_ssl or mod_nss is loaded
    {{ apache_bin_dir }}/httpd -M | egrep 'ssl_module|nss_module'
  register: ssl_nss_check
  ignore_errors: yes

- name: Set compliance status for SSL/NSS modules
  set_fact:
    ssl_nss_status: "{{ 'compliant' if ssl_nss_check.stdout else 'non-compliant' }}"

- name: Record compliance status for SSL/NSS modules
  lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},7.1,ssl_nss_module_status,{{ ssl_nss_status }}"
    create: yes
  delegate_to: localhost
