- name: Set Default
  ansible.builtin.set_fact:
    rewrite_status: "not compliant"


- name: Verify there is a rewrite condition within the global server context
  ansible.builtin.shell: |
    if grep -q 'RewriteEngine On' {{ apache_conf_dir }}/conf/*.conf && \
       grep -q 'RewriteCond %{THE_REQUEST} !HTTP/1\.1$' {{ apache_conf_dir }}/conf/*.conf; then
      echo "Rewrite condition is set"
    else
      echo "Rewrite condition is NOT set" && exit 1
    fi
  register: rewrite_check
  ignore_errors: yes


- name: Set the rewrite status
  ansible.builtin.set_fact:
    rewrite_status: "{{ 'not compliant' if rewrite_check.rc != 0 else 'compliant' }}"
  ignore_errors: yes


- name: Log the compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},5.9,Rewrite Checks,{{ rewrite_status | trim }}"
    create: yes
  delegate_to: localhost
