- name: Set Default
  ansible.builtin.set_fact:
    error_desc: ""
    options_status: "check failed"


- name: Check for root <Directory> element in Apache configuration files
  ansible.builtin.shell: |
    awk '/<Directory/,/<\/Directory/' {{ apache_conf_dir }}/conf/httpd.conf {{ apache_conf_dir }}/conf.d/*.conf
  register: directory_check
  changed_when: false
  ignore_errors: yes

- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ directory_check.stderr }}"
  when: directory_check.rc != 0
  ignore_errors: yes

- name: Set Options compliance status
  ansible.builtin.set_fact:
    options_status: >-
      {%- if directory_check.stdout | regex_search('Options None') -%}
        compliant
      {%- else -%}
        not compliant
      {%- endif -%}
  ignore_errors: yes


- name: Append Options compliance status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.1,directory_options,{{ options_status | trim }}, {{ error_desc | trim }}"
  delegate_to: localhost
  