- name: Set Default
  ansible.builtin.set_fact: 
    options_status: "not compliant"


- name: Check for <Directory> elements in Apache configuration files
  ansible.builtin.shell: |
    perl -ne 'print if /^ *<Directory */i .. /<\/Directory/i' {{ apache_conf_dir }}/conf/httpd.conf {{ apache_conf_dir }}/conf.d/*.conf
  register: directory_check
  changed_when: false
  ignore_errors: yes


- name: Set Options compliance status for Includes
  ansible.builtin.set_fact:
    options_status: >-
      {%- if directory_check.stdout | regex_search('Options.*Includes') -%}
        not compliant
      {%- else -%}
        compliant
      {%- endif -%}
  ignore_errors: yes


- name: Append Options compliance status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},5.3,directory_options_includes,{{ options_status | trim }}"
    insertafter: EOF
  delegate_to: localhost