---
- name: Check for AllowOverride directives in Apache configuration files
  ansible.builtin.shell: |
    grep -i 'AllowOverride' {{ apache_conf_dir }}/conf/httpd.conf {{ apache_conf_dir }}/conf.d/*.conf
  register: allow_override_check
  changed_when: false
  ignore_errors: yes

- name: Set AllowOverride compliance status
  ansible.builtin.set_fact:
    allow_override_status: >-
      {%- if allow_override_check.stdout | regex_search('AllowOverride None') -%}
        compliant
      {%- else -%}
        not_compliant
      {%- endif -%}

- name: Check for AllowOverrideList directives
  ansible.builtin.shell: |
    grep -i 'AllowOverrideList' {{ apache_conf_dir }}/conf/httpd.conf {{ apache_conf_dir }}/conf.d/*.conf
  register: allow_override_list_check
  changed_when: false
  ignore_errors: yes

- name: Set AllowOverrideList compliance status
  ansible.builtin.set_fact:
    allow_override_list_status: >-
      {%- if allow_override_list_check.stdout | length == 0 -%}
        compliant
      {%- else -%}
        not_compliant
      {%- endif -%}

- name: Determine overall compliance status
  ansible.builtin.set_fact:
    overall_status: >-
      {%- if allow_override_status == 'compliant' and
             allow_override_list_status == 'compliant' -%}
        compliant
      {%- else -%}
        not_compliant
      {%- endif -%}

- name: Append AllowOverride compliance status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},4.4,allow_override,{{ overall_status | trim }}"
  delegate_to: localhost
  
- name: Display compliance status for AllowOverride directives
  ansible.builtin.debug:
    msg: "AllowOverride status: {{ allow_override_status }}, AllowOverrideList status: {{ allow_override_list_status }} on {{ inventory_hostname }}"
