- name: Set Default
  ansible.builtin.set_fact: 
    allow_override_status: "not compliant"
    allow_override_list_status: "not compliant"
    overall_status: "not compliant"


- name: Extract root <Directory> element from Apache configuration files
  ansible.builtin.shell: |
    perl -ne 'print if /^ *<Directory *\//i .. /<\/Directory/i' {{ apache_conf_dir }}/conf/httpd.conf
  register: directory_element
  changed_when: false
  ignore_errors: yes

- name: Set AllowOverride compliance status
  ansible.builtin.set_fact:
    allow_override_status: >-
      {%- if directory_element.stdout | regex_search('AllowOverride None') -%}
        compliant
      {%- else -%}
        not compliant
      {%- endif -%}
  ignore_errors: yes 


- name: Check for AllowOverrideList directives
  ansible.builtin.shell: |
    grep -i 'AllowOverrideList' {{ apache_conf_dir }}/conf/httpd.conf
  register: allow_override_list_check
  changed_when: false
  ignore_errors: yes

- name: Set AllowOverrideList compliance status
  ansible.builtin.set_fact:
    allow_override_list_status: >-
      {%- if allow_override_list_check.stdout | length == 0 -%}
        compliant
      {%- else -%}
        not_compliant
      {%- endif -%}
  ignore_errors: yes


- name: Determine overall compliance status
  ansible.builtin.set_fact:
    overall_status: >-
      {%- if allow_override_status == 'compliant' and
              allow_override_list_status == 'compliant' -%}
        compliant
      {%- else -%}
        not_compliant
      {%- endif -%}
  ignore_errors: yes 


- name: Append AllowOverride compliance status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},4.3,allow_override,{{ overall_status | trim }}"
  delegate_to: localhost
