- name: Set Default
  ansible.builtin.set_fact:
    proxy_modules_status: "check failed"


- name: Check if proxy modules are enabled
  ansible.builtin.shell: "{{ apache_bin_dir }}/httpd -M | grep proxy_"
  register: proxy_modules_check
  changed_when: false
  failed_when: proxy_modules_check.rc == 0  
  ignore_errors: true


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ proxy_modules_check.stderr }}"
  when: proxy_modules_check.rc != 0
  ignore_errors: yes

- name: Determine proxy modules status
  ansible.builtin.set_fact:
    proxy_modules_status: "{{ 'not compliant' if proxy_modules_check.rc == 0 else 'compliant' }}"
  ignore_errors: true


- name: Append proxy modules status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},2.6,proxy_modules,{{ proxy_modules_status | trim }}, {{ error_desc | trim }}"
    insertafter: EOF
  delegate_to: localhost