
- name: Search for the SSLCompression directive in Apache configuration
  shell: |
    grep -i "SSLCompression" {{ apache_conf_dir }}/conf/httpd.conf
  register: ssl_compression_check
  ignore_errors: yes

- name: Search for the SSLCompression directive in Apache configuration
  shell: |
    grep -i "SSLCompression\s+off$" {{ apache_conf_dir }}
  register: ssl_compression_off_check
  ignore_errors: yes

- name: Set compliance status for SSLCompression directive
  set_fact:
    ssl_compression_status: "{{ 'compliant' if ssl_compression_check.rc == 1 or ssl_compression_off_check.rc == 0 else 'not compliant' }}"

- name: Record compliance status for SSLCompression directive
  lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},7.7,ssl_compression_status,{{ ssl_compression_status | trim }}"
    create: yes
  delegate_to: localhost
