- name: Locate Apache configuration files including conf.d directory
  ansible.builtin.find:
    paths: "{{ apache_conf_dir }}/conf.d"
    patterns: "*.conf"
  register: apache_config_files

- name: Check RequestReadTimeout directives in Apache configuration
  ansible.builtin.command: grep -Ei '^\s*RequestReadTimeout\s+header=(20|[2-3][0-9]|40)-40,MinRate=500\s+body=(20|[2-3][0-9]|40),MinRate=500' {{ item.path }}
  register: request_read_timeout_check
  loop: "{{ apache_config_files.files }}"
  ignore_errors: yes

- name: Determine compliance status for RequestReadTimeout
  ansible.builtin.set_fact:
    timeout_status: >-
      {% if apache_config_files.files | length == 0 %}
        not_compliant
      {% elif request_read_timeout_check.results | default([]) %}
        compliant
      {% else %}
        not_compliant
      {% endif %}

- name: Write compliance status to CSV
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    line: "{{ inventory_hostname }},9.5,RequestReadTimeout,{{ timeout_status | trim }}"
  delegate_to: localhost
