- name: Set Default
  ansible.builtin.set_fact:
    error_desc: ""
    userdir_status: "check failed"


- name: Check if User Directories module is enabled
  ansible.builtin.shell: "{{ apache_bin_dir }}/apachectl -M | grep userdir_"
  register: userdir_check
  failed_when: userdir_check.rc != 0 
  changed_when: false
  ignore_errors: true


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ userdir_check.stderr }}"
  when: userdir_check.rc != 0
  ignore_errors: yes


- name: Determine User Directories module status
  ansible.builtin.set_fact:
    userdir_status: "{{ 'compliant' if userdir_check.rc == 0 else 'not compliant' }}"
  ignore_errors: true


- name: Append User Directories module status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},2.7,userdir,{{ userdir_status | trim }}, {{ error_desc | trim }}" 
    insertafter: EOF
  delegate_to: localhost
