- name: Set Default
  ansible.builtin.set_fact:
    error_desc: ""
    webdav_status: "check failed"


- name: Check if webdav module is enabled
  ansible.builtin.shell: "{{ apache_bin_dir }}/apachectl -M | grep dav"
  register: webdav_check
  failed_when: webdav_check.rc != 0  
  changed_when: false
  ignore_errors: true


- name: Set error description
  ansible.builtin.set_fact:
    error_desc: "{{ webdav_check.stderr }}"
  when: webdav_check.rc != 0
  ignore_errors: yes


- name: Determine webdav status
  ansible.builtin.set_fact:
    webdav_status: "{{ 'compliant' if webdav_check.rc == 0 else 'not compliant' }}"
  ignore_errors: true


- name: Append webdav status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},2.3,webdav,{{ webdav_status | trim }}, {{ error_desc | trim }}"
    insertafter: EOF
  delegate_to: localhost