---
- name: Check if webdav module is enabled
  ansible.builtin.shell: "{{ apache_bin_dir }}/apachectl -M | grep dav"
  register: webdav_check
  failed_when: webdav_check.rc != 0  
  changed_when: false
  ignore_errors: true

- name: Determine webdav status
  ansible.builtin.set_fact:
    webdav_status: "{{ 'compliant' if webdav_check.rc == 0 else 'not compliant' }}"

- name: Append webdav status to CSV file
  ansible.builtin.lineinfile:
    path: "{{ csv_file }}"
    create: yes
    line: "{{ inventory_hostname }},2.3,webdav,{{ webdav_status | trim }}"
    insertafter: EOF
  delegate_to: localhost
  
- name: Display webdav status
  ansible.builtin.debug:
    msg: "WebDAV module is {{ webdav_status }} on {{ inventory_hostname }}"
